export { apiErrorSchema } from './schemas/common.js'
export type { ApiError } from './schemas/common.js'
export { createUserSchema, updateUserSchema } from './schemas/user.js'
export type { CreateUser, UpdateUser } from './schemas/user.js'
export { createCalendarSchema, updateCalendarSchema } from './schemas/calendar.js'
export type { CreateCalendar, UpdateCalendar } from './schemas/calendar.js'
export { createEventSchema, updateEventSchema } from './schemas/event.js'
export type { CreateEvent, UpdateEvent } from './schemas/event.js'

export type { ApiResponse, ListResponse } from './types/api.js'
export type { User } from './types/user.js'
export { EventType, EventStatus, EventVisibility, ExceptionType, EVENT_TYPE_VALUES, EVENT_STATUS_VALUES, EVENT_VISIBILITY_VALUES, EXCEPTION_TYPE_VALUES } from './types/event.js'
export { CalendarPermission, CALENDAR_PERMISSION_VALUES } from './types/calendar.js'

export { DEFAULT_EVENT_DURATION } from './constants/defaults.js'
export { CALENDAR_COLORS } from './constants/colors.js'
export type { CalendarColor } from './constants/colors.js'
export { ACCENT_COLOR_PRESETS, DEFAULT_ACCENT_COLOR } from './constants/accent-colors.js'
export type { AccentColorPreset } from './constants/accent-colors.js'
